---
labels:
  # Areas
  - name: area/bootstrap
    color: '0e8a16'
  - name: area/docs
    color: '0e8a16'
  - name: area/github
    color: '0e8a16'
  - name: area/kubernetes
    color: '0e8a16'
  - name: area/renovate
    color: '0e8a16'
  - name: area/scripts
    color: '0e8a16'
  - name: area/talos
    color: '0e8a16'
  - name: area/taskfile
    color: '0e8a16'
  - name: area/templates
    color: '0e8a16'
